name: Eve Burchfield
favicon: null
layout_spectrum: 0.8249630248174071
typography_spectrum: 0.07079538586549461
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.48993680626153946
  lightness: 0.4429429753217846
  saturation: 0.20108003146015108
  rhythmicContrast: 0.3249639489222318
purpose: []
